### ISSUE TITLE
Suggestion: replace `log` with `tracing`

### ISSUE THREAD

**Issue by JasmineLowen** [kliarist/animals#2]
Hey,

first of all: Really cool template/example repo you're working on here! I love the simplicity and that everything is easy to understand.

While looking into the code I noticed you were using the `log` crate. I just wanted to suggest to replace

- `log` with `tracing`
- `env_logger` with `tracing_subscriber`

They replacement crates have a very similar interface and it shouldn't be hard at all. Generally it seems that these replacements are the new rust ecosystem standards for logging. But on the other hand maybe you're using `log` and `env_logger` for a specific reason. In this case, feel free to ignore and close this issue here 😊

**Comment by kliarist** [comment]
@RobWalt first of all, thanks for taking the time to take a look!

Sure, I can follow your suggestions. Also, I think it might make sense to encourage PRs if of course you have capacity.

Thanks again

**Comment by JasmineLowen** [comment]
Yeah sure, I'll give it a try :+1:

**Comment by kliarist** [comment]
@RobWalt added that
